### ISSUE TITLE
Copier URL Post

### ISSUE THREAD

**Issue by Wiripse** [Aynolor/SuperHFRplus#11]
En se mettant sur le détail d’un post, bouton partager puis copier le lien, dans le clipboard on a un truc crade comme ça :

`actionLink URL = https://forum.hardware.fr/forum2.php?config=hfr.inc&cat=13&subcat=432&post=61999&page=2635&p=1&sondage=0&owntopic=1&trash=0&trash_post=0&print=0&numreponse=0&quote_only=0&new=0&nojs=0#t54589445`

Alors que l'on souhaite récupérer uniquement l'URL

**Comment by Aynolor** [comment]
#10
