### ISSUE TITLE
Super favoris : pouvoir taguer certains favoris pour qu'ils apparaissent de manière encore plus évidente

### ISSUE THREAD

**Issue by ezzz** [Aynolor/SuperHFRplus#21]
Deux concepts pour améliorer la gestion des favoris 
- super favori : qui serait affiché en priorité (à voir comment: une icône spécifique, affiché en haut de cat, affiché toujours dans la liste des favoris même s'il est lu...) 
- de favori "moins favori" : afin de pouvoir garder le drapeau sur un topic pour y revenir de temps en temps mais sans qu’il soit constamment affiché: ajout d'un toggle bouton pour masquer/afficher ces topics ?

**Comment by Wiripse** [comment]
C'est une excellente idée !

Pourquoi ne pas utiliser MPStorage ? https://github.com/Wiripse/HFRGMTools
