### ISSUE TITLE
Télécharger l'intégralité non lue d'un sujet pour lecture offline

### ISSUE THREAD

**Issue by Romfour** [Aynolor/SuperHFRplus#55]
Ce serait parfait pour utilisation dans les transports en général, métro quand la connexion est mauvaise, avion....
Perso je passe mon temps de métro à rattraper certains sujets, mais assez souvent limité par la connectivité.
Merci :)

**Comment by Wiripse** [comment]
Si dans la partie "non lue" il y a un quote vers un post déjà lu, quel comportement adopter quand on clique sur le quote ? Ça plante ? On ne fait rien ? On est redirigé vers le post quoté mais dans ce cas il faut charger du nouveau contenu ?

**Comment by Romfour** [comment]
Un petit message du genre "contenu non disponible offline", pour commencer?
En plus le quote lui s'affichera donc ça permet quand même d'avoir une idée sur ce à quoi le post répondait :)
