### ISSUE TITLE
Format heure et calcul elapsed time

### ISSUE THREAD

**Issue by Wiripse** [Aynolor/SuperHFRplus#60]
Lorsque le device est réglé pour afficher l'heure au format 12h (AM/PM), le calcul du temps écoulé depuis que le dernier message d'un topic a été posté ne fonctionne pas. Affiche toujours "il y a 1min".

Le problème ne concerne que les messages postés le jour même, puisque les messages de la veille ou avant, c'est la date qui est affichée.

**Comment by ezzz** [comment]
Fixé en 2.1.10
