### ISSUE TITLE
Ne pas créer de drapal pour les MP simples

### ISSUE THREAD

**Issue by Wiripse** [Aynolor/SuperHFRplus#62]
La feature drapeaux Dark Topic ne doit concerner que les MP avec au moins trois intervenants 

Lorsque la discussion n'est qu'entre deux personnes, le principe de drapeau n'est pas intéressant et ajoute des données dans le JSON alors que la place est chère

**Comment by Wiripse** [comment]
Pour info dans HFR4K j'ai procédé de la sorte pour savoir facilement si un MP est un DT ou un simple MP

https://github.com/Wiripse/HFRGMTools/blob/265ca344a6a844faac594367775c378d33b2985f/beta/HFR4K.user.js#L2195

**Comment by Wiripse** [comment]
Feuk j'avais bricolé un workaround en rajoutant "isDT" sur les flags correspondant réellement à des DT, pour pouvoir distinguer facilement les flags DT des flags MPs, sauf que dans HFR+ un flag n'est pas mis à jour, il est remplacé. Et évidemment dans la version remplacée le "isDT" est dégagé. Résultat ça redevient un flag lambda.
Il n'y a que si je détecte une mise à jour (lecture d'un message plus récent que celui stocké) que je rajoute "isDT" et retrouve un fonctionnement correcte de HFR4K.

**Comment by ezzz** [comment]
Fixé en 2.1.11

**Comment by Wiripse** [comment]
Merci
